export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts}"
  ],
  darkMode: "class",
  theme: {
    extend: {
        colors: {
            "secondary-dim": "#1153a1",
            "error-container": "#f95630",
            "inverse-surface": "#0a111a",
            "background": "#f8fbff",
            "on-tertiary-fixed": "#002a4a",
            "on-primary": "#ffffff",
            "tertiary-container": "#d6e6f9",
            "surface-container-high": "#e1edf9",
            "on-primary-fixed-variant": "#00478a",
            "surface-tint": "#1978e5",
            "tertiary-fixed": "#d6e6f9",
            "outline-variant": "#cad4e0",
            "primary-fixed-dim": "#86b7f3",
            "outline": "#717882",
            "surface-container-low": "#f0f5fa",
            "primary": "#1978e5",
            "primary-fixed": "#d3e4ff",
            "on-tertiary": "#ffffff",
            "surface-dim": "#d8e1e9",
            "on-surface-variant": "#44474e",
            "surface-container-highest": "#dce4eb",
            "secondary": "#1978e5",
            "on-tertiary-fixed-variant": "#00325b",
            "secondary-fixed-dim": "#86b7f3",
            "error-dim": "#b92902",
            "error": "#be2d06",
            "surface-container": "#eef2f6",
            "surface": "#f8fbff",
            "secondary-container": "#d3e4ff",
            "on-secondary-fixed-variant": "#00478a",
            "on-primary-container": "#001b3d",
            "surface-variant": "#dfe2eb",
            "on-tertiary-container": "#001e30",
            "tertiary-fixed-dim": "#adcbe6",
            "on-error": "#ffffff",
            "inverse-primary": "#d3e4ff",
            "primary-dim": "#1565c0",
            "on-primary-fixed": "#001b3d",
            "on-secondary": "#ffffff",
            "on-surface": "#1a1c1e",
            "inverse-on-surface": "#f0f0f3",
            "on-secondary-container": "#001b3d",
            "on-background": "#1a1c1e",
            "tertiary": "#1978e5",
            "on-error-container": "#520c00",
            "primary-container": "#d3e4ff",
            "surface-bright": "#f8fbff",
            "surface-container-lowest": "#ffffff",
            "tertiary-dim": "#1978e5",
            "secondary-fixed": "#d3e4ff",
            "on-secondary-fixed": "#001b3d"
        },
        fontFamily: {
            "headline": ["Inter"],
            "body": ["Inter"],
            "label": ["Inter"]
        },
        borderRadius: {"DEFAULT": "4px", "lg": "4px", "xl": "4px", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}